## 1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [1]:
import numpy as np

In [16]:
n = np.zeros((10,), dtype=np.int)
# n = np.zeros(shape=10,dtype=np.int)
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
n[4] = 1
n

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## 2、创建一个元素为从10到49的ndarray对象

In [19]:
n = np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3、将第2题的所有元素位置反转

In [20]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [13]:
n=np.random.random(size=(10,10))
n
# display(n.max(),n.min())

array([[ 0.13071628,  0.55207926,  0.42386168,  0.04623197,  0.61339532,
         0.51320637,  0.98017978,  0.75142085,  0.15421525,  0.81504192],
       [ 0.63101744,  0.75066924,  0.75575464,  0.90884768,  0.18912599,
         0.73272496,  0.62247733,  0.29151288,  0.29262886,  0.8882371 ],
       [ 0.54556844,  0.6813773 ,  0.181502  ,  0.54677826,  0.20757744,
         0.36695285,  0.36486729,  0.09594806,  0.2760189 ,  0.77246564],
       [ 0.12619807,  0.62712373,  0.81185366,  0.6107853 ,  0.85328452,
         0.3717048 ,  0.58720316,  0.17762297,  0.67754822,  0.35673785],
       [ 0.46150748,  0.80420751,  0.28326874,  0.90578257,  0.12685943,
         0.08491297,  0.7147351 ,  0.68168657,  0.20259989,  0.28276729],
       [ 0.17531374,  0.84342199,  0.80010369,  0.25557353,  0.19239459,
         0.61102991,  0.2497539 ,  0.2939386 ,  0.10456557,  0.025002  ],
       [ 0.47543563,  0.98168254,  0.22037206,  0.58171402,  0.48791882,
         0.93752301,  0.99899906,  0.06983531

In [15]:
n.max()

0.99899906494325563

In [16]:
n.min()

0.015406596905060854

## 5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [17]:
# 方法一
m=[1,0,0,0,0,0,0,0,0,1]
a=np.array(m)
a

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [19]:
n = a.reshape(10,1)
n

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [26]:
x=a + n
x[0,0]=1
x[0,9]=1
x[9,0]=1
x[9,9]=1
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
# 方法二
n = np.ones((10,10),dtype=int)
n[1:-1,1:-1] = 0
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## 6、创建一个每一行都是从0到4的5*5矩阵

In [32]:
l=[0,1,2,3,4]
a=np.array(l)
a

array([0, 1, 2, 3, 4])

In [34]:
b=np.zeros(shape=(1,5),dtype=int)
c=b.reshape(5,1)
c

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [35]:
a + c

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [25]:
# 方式二
n1 = np.arange(0,5)
n2 = np.zeros(5, dtype=int).reshape((5,1))
n1+n2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## 7、创建一个范围在(0,1)之间的长度为12的等差数列

In [40]:
n=np.linspace(0, 1, num=12, endpoint=False, retstep=True)
n

(array([ 0.        ,  0.08333333,  0.16666667,  0.25      ,  0.33333333,
         0.41666667,  0.5       ,  0.58333333,  0.66666667,  0.75      ,
         0.83333333,  0.91666667]), 0.08333333333333333)

## 8、创建一个长度为10的随机数组并排序

In [44]:
a=np.random.randint(100,size=(10,))
a.sort()
a

array([16, 34, 40, 49, 59, 68, 79, 80, 94, 94])

## 9、创建一个长度为10的随机数组并将最大值替换为0

In [45]:
a[9]=0
a

array([16, 34, 40, 49, 59, 68, 79, 80, 94,  0])

## 10、如何根据第3列来对一个5*5矩阵排序？

In [3]:
n1=np.random.randint(100,size=(5,5))
n1

array([[46, 61, 26, 38,  8],
       [31, 85, 66, 49, 63],
       [96, 28, 44, 30, 50],
       [50, 16, 62,  7, 84],
       [76, 59, 60, 60, 99]])

In [4]:
# 对第三列进行排序
n1=n1[np.argsort(n1[:,2])]
n1

array([[46, 61, 26, 38,  8],
       [96, 28, 44, 30, 50],
       [76, 59, 60, 60, 99],
       [50, 16, 62,  7, 84],
       [31, 85, 66, 49, 63]])

## 11、给定一个4维矩阵，如何得到最后两维的和？

In [17]:
n2=np.random.randint(100,size=(4,4))
n2, n2.sum((-1,-2))
# 这个版本没有display但是可以逗号间隔输出

(array([[41, 53, 12, 24],
        [34, 63, 74, 10],
        [12, 75, 94,  4],
        [61, 20, 22, 97]]), 696, 1)

## 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [18]:
nd1=np.arange(1,6)
nd2=np.zeros(shape=17,dtype=int)
nd2[::4]=nd1
nd2
# 创建0list插入数字

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

## 13、给定一个二维矩阵，如何交换其中两行的元素？

In [20]:
n = np.random.randint(100,size=(3,4))
n

array([[26, 13, 54, 14],
       [51, 66, 59, 48],
       [31, 85, 68, 24]])

In [23]:
n[1],n[2]=n[2].copy(),n[1].copy()
n

array([[26, 13, 54, 14],
       [31, 85, 68, 24],
       [51, 66, 59, 48]])

## 14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [26]:
np.random.randint(100000,size=100000)
%time np.power(n,3)
%time n**3

CPU times: user 31 µs, sys: 9 µs, total: 40 µs
Wall time: 47.4 µs
CPU times: user 30 µs, sys: 0 ns, total: 30 µs
Wall time: 36.7 µs


array([[ 17576,   2197, 157464,   2744],
       [ 29791, 614125, 314432,  13824],
       [132651, 287496, 205379, 110592]])

## 15、创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积

In [2]:
n1 = np.random.randint(100,size=(5,3))
n2 = np.random.randint(100,size=(3,2))
display(n1, n2)
np.dot(n1, n2)

array([[73, 90, 65],
       [88, 13, 27],
       [84, 88, 31],
       [45, 44, 67],
       [35, 86, 66]])

array([[82, 28],
       [94, 47],
       [40, 88]])

array([[17046, 11994],
       [ 9518,  5451],
       [16400,  9216],
       [10506,  9224],
       [13594, 10830]])

## 16、矩阵的每一行的元素都减去该行的平均值

In [3]:
n = np.random.randint(100,size=(4,4))
display(n)
n_mean = n.mean(1).reshape(4,1)
display(n_mean)
n - n_mean

array([[ 8, 17, 48,  6],
       [96, 87, 90, 97],
       [ 3, 56, 27, 11],
       [11, 86, 32, 13]])

array([[19.75],
       [92.5 ],
       [24.25],
       [35.5 ]])

array([[-11.75,  -2.75,  28.25, -13.75],
       [  3.5 ,  -5.5 ,  -2.5 ,   4.5 ],
       [-21.25,  31.75,   2.75, -13.25],
       [-24.5 ,  50.5 ,  -3.5 , -22.5 ]])

## 17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：

In [ ]:
# [[0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]]
#  Z[1::2,::2] = 1
# Z[::2,1::2] = 1

In [15]:
n=np.zeros(shape=(8,8), dtype=int)
n[1::2,::2] = 1  # 二维数组[第一层定位(包含步长):第二层定位(包含步长)]
n[::2,1::2] = 1
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 18、正则化一个5*5随机矩阵正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

In [4]:
n = np.random.randint(100,size=(5,5))
# display(n)
n = (n - n.min())/(n.max() - n.min())
n

array([[0.51162791, 0.5       , 0.62790698, 1.        , 0.41860465],
       [0.        , 0.74418605, 0.05813953, 0.39534884, 0.81395349],
       [0.1744186 , 0.41860465, 0.13953488, 0.05813953, 0.84883721],
       [0.76744186, 0.41860465, 0.95348837, 0.48837209, 0.63953488],
       [0.25581395, 0.45348837, 0.41860465, 0.58139535, 0.25581395]])

## 19、将一个一维数组转化为二进制表示矩阵。例如[1,2,3]转化为

In [ ]:
# [[0,0,1],
# [0,1,0],
# [0,1,1]]

## 20、实现快速和选择排序法

In [6]:
# 选择排序
def select_sort(n):
    for i in range(len(n)-1):
        index = n[i:].argmin() + i
        if n[i] > n[index]:
            n[i], n[index] = n[index], n[i]
    return n

n = np.random.randint(100, size=(10))
result = select_sort(n)
display(result)

array([34, 49, 52, 58, 66, 66, 70, 81, 85, 97])

In [8]:
# 快速排序
n1 = np.random.randint(100,size=(10))
n1

for i in range(len(n1)):
    for j in range(len(n1) - 1):
        if n1[i] < n1[j]:
            n1[i], n1[j] = n1[j], n1[i]
n1

array([25, 26, 29, 35, 38, 48, 50, 68, 87, 97])