In [5]:
import numpy as np

## 1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [12]:
n1 = np.zeros(10,dtype=np.int)
n1[4] = 1
n1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## 2、创建一个元素为从10到49的ndarray对象

In [14]:
n2 = np.arange(10, 50)
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3、将第2题的所有元素位置反转

In [15]:
n3 = n2[::-1]
n3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [20]:
n4 = np.random.random(size=(10,10))
n4

array([[0.09394215, 0.59768865, 0.96206182, 0.62049968, 0.56343989,
        0.77942895, 0.56076755, 0.09404869, 0.6327115 , 0.69832407],
       [0.58214802, 0.20077386, 0.55529304, 0.97317717, 0.31452708,
        0.46602955, 0.11368712, 0.4364268 , 0.52207165, 0.80782498],
       [0.96618614, 0.77755802, 0.02471698, 0.57289443, 0.53086373,
        0.13046213, 0.15718837, 0.63754282, 0.3399047 , 0.0747503 ],
       [0.16185038, 0.32630927, 0.69243725, 0.73824191, 0.89668902,
        0.93853078, 0.63855415, 0.42366342, 0.10982353, 0.24431599],
       [0.90681933, 0.54337598, 0.52607947, 0.92000248, 0.50261199,
        0.28673832, 0.84470742, 0.13588831, 0.37780111, 0.2782386 ],
       [0.78040063, 0.39023093, 0.14793331, 0.73723438, 0.72004446,
        0.84187737, 0.42353364, 0.47456267, 0.04223742, 0.19910058],
       [0.19830314, 0.72468138, 0.04153713, 0.80868955, 0.51926081,
        0.02289204, 0.04696568, 0.05968607, 0.53867683, 0.80441796],
       [0.34061882, 0.4666112 , 0.6002997

In [21]:
n4.max()

0.9980505951555044

In [22]:
n4.min()

0.022892040855150952

## 5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [35]:
n5 = np.ones((10,10), dtype=np.int)
n5[1:-1, 1:-1] = 0
n5

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## 6、创建一个每一行都是从0到4的5*5矩阵

In [56]:
n5 = [0,1,2,3,4]
n5 = np.array(n5*5)
n5.reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## 7、创建一个范围在(0,1)之间的长度为12的等差数列

In [58]:
n7 = np.random.rand(12)
n7

array([0.79079348, 0.00248118, 0.67636107, 0.64839542, 0.31871339,
       0.50908833, 0.28856299, 0.01844673, 0.2518857 , 0.82229114,
       0.28121559, 0.0318449 ])

## 8、创建一个长度为10的随机数组并排序

In [70]:
n8 = np.random.randint(100,size=10)
n8 = np.sort(n8)
n8

array([13, 15, 18, 19, 24, 34, 35, 42, 45, 66])

## 9、创建一个长度为10的随机数组并将最大值替换为0

In [71]:
n9 = np.random.randint(100,size=10)
n9 = np.sort(n9)
n9[-1] = 0
n9

array([ 7, 11, 12, 15, 42, 64, 72, 81, 84,  0])

## 10、如何根据第3列来对一个5*5矩阵排序？

In [76]:
n10 = np.random.randint(100,size=(5, 5))

n10

array([[97,  0, 95, 65, 22],
       [53, 96, 84, 76, 79],
       [51, 13, 31, 56, 63],
       [47,  6, 64, 22, 49],
       [70, 95, 54, 84, 10]])

## 11、给定一个4维矩阵，如何得到最后两维的和？

In [4]:
n11 = np.random.randint(100,size=(2, 2, 3, 3))
n11


array([[[[29, 45, 72],
         [56, 25, 61],
         [76, 33, 55]],

        [[18, 14, 16],
         [37, 64, 63],
         [77, 97, 98]]],


       [[[53, 85, 54],
         [28, 48,  0],
         [35, 72,  7]],

        [[47, 43, 82],
         [78, 90, 84],
         [59, 41, 50]]]])

In [5]:
n3 = np.random.randint(100, size=(3,4,5))
n3

array([[[38, 18, 37, 97, 59],
        [30, 57, 90, 41, 23],
        [63, 42, 27, 64, 61],
        [67, 87, 82, 38, 93]],

       [[35, 27, 26, 68, 56],
        [ 5, 22, 13, 73, 41],
        [97, 19,  6, 61, 11],
        [90, 71, 80, 41, 14]],

       [[48,  6, 39, 27, 99],
        [56,  0, 83, 91, 39],
        [89, 25, 56, 53, 15],
        [59, 70, 14, 21, 42]]])

In [2]:
import numpy as np

## 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [219]:
n12 = np.arange(1,6)
n12 = np.vstack(n12)
n121 = np.zeros(shape=(5,3),dtype=np.int)
n12 = np.hstack((n12,n121))
n12.reshape(20)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

## 13、给定一个二维矩阵，如何交换其中两行的元素？

In [121]:
n13 = np.random.randint(100,size=(5,5))
n13

array([[73, 30, 39, 29, 81],
       [ 5, 33, 59, 19, 83],
       [85, 42, 67, 48,  7],
       [15, 41,  1, 86, 45],
       [52, 56, 72, 37, 27]])

In [122]:
n13[[0,3,2,1,4]]

array([[73, 30, 39, 29, 81],
       [15, 41,  1, 86, 45],
       [85, 42, 67, 48,  7],
       [ 5, 33, 59, 19, 83],
       [52, 56, 72, 37, 27]])

## 14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [195]:
%time n14 = np.random.randint(100,size=100000)
n14**3 

Wall time: 997 µs


array([ 42875,   1000,      0, ..., 778688,  97336, 300763], dtype=int32)

In [196]:
%time n14 = np.array(n14*n14*n14)
n14

Wall time: 1 ms


array([ 42875,   1000,      0, ..., 778688,  97336, 300763])

## 15、创建一个5\*3随机矩阵和一个3\*2随机矩阵，求矩阵积

In [133]:
n151 = np.random.randint(100, size=(5,3))
n151

array([[ 9, 13,  7],
       [84, 57, 51],
       [70,  5, 16],
       [88,  1, 52],
       [79, 20, 37]])

In [135]:
n152 = np.random.randint(100, size=(3,2))
n152

array([[85, 99],
       [92, 17],
       [69,  0]])

In [136]:
n15 = np.dot(n151,n152)
n15

array([[ 2444,  1112],
       [15903,  9285],
       [ 7514,  7015],
       [11160,  8729],
       [11108,  8161]])

## 16、矩阵的每一行的元素都减去该行的平均值

In [138]:
n16 = np.random.randint(100, size=(5,5))
n16

array([[10, 23,  7, 24, 40],
       [33, 93, 82, 87, 12],
       [72, 99, 45, 43, 58],
       [70, 98, 76, 44, 88],
       [23, 38, 95, 59, 76]])

In [180]:
n161 = np.mean(n16, axis=1)
n16 - np.vstack(n161)

array([[-10.8,   2.2, -13.8,   3.2,  19.2],
       [-28.4,  31.6,  20.6,  25.6, -49.4],
       [  8.6,  35.6, -18.4, -20.4,  -5.4],
       [ -5.2,  22.8,   0.8, -31.2,  12.8],
       [-35.2, -20.2,  36.8,   0.8,  17.8]])

## 17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：
'''
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
'''


In [188]:
n17 = np.zeros(shape=(8,8),dtype=np.int)
n17[1::2,::2] = 1
n17[::2,1::2] = 1
n17

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 18、正则化一个5*5随机矩阵
## 正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

In [192]:
n18 = np.random.randint(100, size=(5,5))
nmax = n18.max()
nmin = n18.min()
n18 = (n18-nmin)/(nmax-nmin)
n18

array([[0.11340206, 0.        , 0.72164948, 0.92783505, 0.40206186],
       [0.12371134, 0.53608247, 0.81443299, 0.34020619, 0.55670103],
       [0.80412371, 0.82474227, 0.12371134, 0.68041237, 0.72164948],
       [0.36082474, 0.92783505, 0.02061856, 0.88659794, 0.27835052],
       [0.42268041, 0.08247423, 1.        , 0.80412371, 0.68041237]])