In [1]:
import numpy as np

1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [2]:
nd = np.array([0,0,0,0,0,0,0,0,0,0])

In [3]:
nd

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
nd[4] = 5

In [12]:
nd

array([0, 0, 0, 0, 5, 0, 0, 0, 0, 0])

2、创建一个元素为从10到49的ndarray对象

In [13]:
nd2 = np.arange(10,50)

In [14]:
nd2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3、将第2题的所有元素位置反转

In [17]:
nd3 = nd2[::-1]

In [18]:
nd3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [31]:
nd4 = np.random.random((10,10))

In [32]:
nd4

array([[0.28885544, 0.24952582, 0.50699004, 0.67329272, 0.64688893,
        0.45911034, 0.77538171, 0.21330254, 0.2641461 , 0.87872   ],
       [0.62947192, 0.11001889, 0.42628505, 0.61009997, 0.89801519,
        0.11375367, 0.60826147, 0.31305484, 0.03763262, 0.46698953],
       [0.97976568, 0.55231509, 0.35623711, 0.88775652, 0.90148017,
        0.79805194, 0.78860667, 0.55059793, 0.85069876, 0.98522993],
       [0.44163306, 0.39691777, 0.41919826, 0.26783464, 0.76780308,
        0.00240151, 0.04986132, 0.43347581, 0.90677411, 0.77830381],
       [0.8326195 , 0.68241968, 0.70931125, 0.04513324, 0.58702506,
        0.62988847, 0.23920797, 0.77052717, 0.21862214, 0.70460174],
       [0.8754181 , 0.10780293, 0.11451435, 0.12248909, 0.27545036,
        0.95979795, 0.47845953, 0.53102301, 0.26424148, 0.13625978],
       [0.64114694, 0.3026188 , 0.27637737, 0.79672455, 0.97936775,
        0.71016521, 0.59458755, 0.4995775 , 0.16984712, 0.68221951],
       [0.76903854, 0.63496082, 0.2056965

In [33]:
nd4_max = nd4.max()
nd4_min = nd4.min()

In [34]:
nd4_max

0.9852299334859811

In [36]:
nd4_min

0.0024015103235651702

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [44]:
nd5 = np.ones((10,10),dtype=int)

In [45]:
nd5

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
nd5[1:-1,1:-1] = 0

In [48]:
nd5

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

6、创建一个每一行都是从0到4的5*5矩阵

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [51]:
nd7 = np.linspace(0,1,12)

In [52]:
nd7

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序

In [53]:
nd8 = np.random.random(10)

In [54]:
nd8.sort()

In [57]:
nd8

array([0.03099414, 0.05704731, 0.12450806, 0.14933547, 0.24333107,
       0.64432165, 0.67977272, 0.80464596, 0.82221214, 0.84892152])

9、创建一个长度为10的随机数组并将最大值替换为0

In [58]:
nd9 = np.random.random(10)

In [59]:
nd9[nd9.argmax()] = 0

In [60]:
nd9

array([0.        , 0.39729684, 0.56799517, 0.02892793, 0.88025029,
       0.24309846, 0.22446215, 0.31554875, 0.59508002, 0.43320094])

10、如何根据第3列来对一个5*5矩阵排序？