1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [2]:
import numpy as np

In [3]:
n=np.array([0,0,0,0,0,0,0,0,0,0])
n[4]=1
n

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2、创建一个元素为从10到49的ndarray对象

In [5]:
n=np.arange(10,49)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

3、将第2题的所有元素位置反转

In [6]:
n[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [11]:
np.random.random(size=(10,10)).min()

0.009893997754164552

In [9]:
np.random.random(size=(10,10)).max()

0.9974631372212679

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [24]:
n=np.full(shape=(10,10),fill_value=0)
n[[0,-1]]=1
n[:,[0,-1]]=1
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

6、创建一个每一行都是从0到4的5*5矩阵

In [33]:
l=[0,1,2,3,4]
n=np.array(l*5)
n.reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [35]:
np.random.random(size=13)

array([0.19609565, 0.9958656 , 0.96820067, 0.72309362, 0.41160609,
       0.6912165 , 0.79314818, 0.53142322, 0.47707252, 0.83280879,
       0.9871869 , 0.13519953, 0.77706078])

In [36]:
np.linspace(0,1,num=12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序

In [48]:
def num(arr):
    for i in range(len(arr)-1):
        index = np.argmin(arr[i:])+i
        if arr[i]>arr[index]:
            arr[i],arr[index] = arr[index],arr[i]
    return arr
a=np.random.random(10)
num(a)

array([0.11216501, 0.11927382, 0.14036071, 0.22770183, 0.3473261 ,
       0.42118627, 0.48928637, 0.54216913, 0.7844817 , 0.96358841])

9、创建一个长度为10的随机数组并将最大值替换为0

In [50]:
n3=np.random.randint(0,10,size=10)
display(n3)
index_max = n3.argmax()

array([2, 9, 4, 5, 0, 5, 1, 8, 3, 5])

10、如何根据第3列来对一个5*5矩阵排序？

In [54]:
n4=np.random.randint(100,size=(5,5))
n4

array([[ 0, 18, 35, 70, 43],
       [53, 67, 86, 82, 29],
       [96, 90, 11, 23, 31],
       [96, 92, 66, 43, 65],
       [74, 20, 95, 60, 47]])

In [56]:
n4[:,2]

array([35, 86, 11, 66, 95])

In [57]:
np.argsort(n4[:,2])

array([2, 0, 3, 1, 4], dtype=int64)

In [59]:
n4[np.argsort(n4[:,2])]

array([[96, 90, 11, 23, 31],
       [ 0, 18, 35, 70, 43],
       [96, 92, 66, 43, 65],
       [53, 67, 86, 82, 29],
       [74, 20, 95, 60, 47]])

11、给定一个4维矩阵，如何得到最后两维的和？

12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [61]:
nd1=np.arange(1,6)
nd2=np.zeros(shape=17,dtype=int)
nd2[::4]=nd1
nd2

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

13、给定一个二维矩阵，如何交换其中两行的元素？

In [73]:
n5=np.random.randint(20,size=(3,4))
n5[[1,0,2]]

array([[ 4, 18,  1,  1],
       [ 7, 18, 16, 15],
       [ 3, 19,  6, 12]])

14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

15、创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积

In [74]:
n6=np.random.randint(100,size=(5,3))
n6

array([[55, 56, 27],
       [77, 69,  8],
       [ 8, 71, 94],
       [24, 32, 33],
       [46, 31, 61]])

In [75]:
n7=np.random.randint(100,size=(3,2))
n7

array([[72, 31],
       [73, 10],
       [33, 45]])

In [77]:
np.dot(n6,n7)

array([[ 8939,  3480],
       [10845,  3437],
       [ 8861,  5188],
       [ 5153,  2549],
       [ 7588,  4481]])

16、矩阵的每一行的元素都减去该行的平均值

17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
 Z[1::2,::2] = 1
Z[::2,1::2] = 1



In [78]:
n9=np.zeros(shape=(8,8))
n9

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

18、正则化一个5*5随机矩阵
正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

19、将一个一维数组转化为二进制表示矩阵。例如
[1,2,3]
转化为
[[0,0,1],
[0,1,0],
[0,1,1]]






20、实现快速和选择排序法