#创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
n1 = np.zeros(10)
n1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
n1[4] =1

In [6]:
n1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2、创建一个元素为从10到49的ndarray对象

In [7]:
n2 = np.random.randint(10,50)
n2

11

#使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [14]:
n3 = np.random.random(size=(10,10))
n3

array([[0.54979391, 0.41296762, 0.72441773, 0.21703743, 0.3732119 ,
        0.53406308, 0.77669356, 0.5369628 , 0.57700895, 0.36900104],
       [0.58773845, 0.84263302, 0.78183076, 0.04469541, 0.42979572,
        0.4178669 , 0.59247811, 0.4099786 , 0.47854116, 0.12728249],
       [0.74871904, 0.35600819, 0.90994967, 0.55187671, 0.23826355,
        0.78527725, 0.24209221, 0.97690173, 0.7465396 , 0.56022951],
       [0.03912797, 0.7231261 , 0.87291159, 0.51958898, 0.63562832,
        0.87307657, 0.45433451, 0.83783188, 0.29774753, 0.85823759],
       [0.68480322, 0.90205401, 0.68107293, 0.18632779, 0.23682073,
        0.93958435, 0.42455891, 0.30296232, 0.84385536, 0.34205163],
       [0.13444274, 0.81340732, 0.13073727, 0.27334355, 0.64007578,
        0.06684291, 0.00986416, 0.15797755, 0.7233966 , 0.4380739 ],
       [0.01896714, 0.8964965 , 0.20926814, 0.01612728, 0.17923084,
        0.40474029, 0.92356393, 0.36112023, 0.07547874, 0.95316181],
       [0.82620395, 0.71752857, 0.44276  

In [15]:
n3.max()

0.9785546288118471

In [16]:
n3.min()

0.007355169886470558

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0```m

In [57]:
n4= np.ones((10,10))
n4[1:-1,1:-1] = 0
n4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 创建一个每一行都是从0到4的5*5矩阵

In [61]:
ad = np.arange(0,25,1)
ad.resize((5,5))
ad
nd1 = np.arange(0,5,1)
ad[0:5] = nd1

ad

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#7、创建一个范围在(0,1)之间的长度为12的等差数列

In [64]:
n6 = np.linspace(0,1,12)
n6

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序

In [68]:
a1 = np.random.random(10)
a1.sort()
a1

array([0.13100932, 0.14378863, 0.16641277, 0.23099279, 0.23639595,
       0.3278731 , 0.46527465, 0.79734971, 0.92919137, 0.9721578 ])

创建一个长度为10的随机数组并将最大值替换为0

In [70]:
a1 = np.random.random(10)
a1[a1.argmax()] =0
a1


array([0.76138357, 0.08380533, 0.17136004, 0.639638  , 0.39606429,
       0.95290976, 0.        , 0.13118133, 0.39054738, 0.86052846])

10、如何根据第3列来对一个5*5矩阵排序？

In [73]:
a4 = np.random.randint(0,20,size=(5,5))
a4

array([[ 8,  0, 17,  3,  7],
       [14, 12, 11, 16, 13],
       [10, 19, 14,  7, 14],
       [10,  4, 14,  1, 19],
       [ 2, 18, 16,  2, 16]])

In [75]:
a5 = np.argsort(a4[:,3])
a5

array([3, 4, 0, 2, 1], dtype=int64)

In [76]:
a4[a5]

array([[10,  4, 14,  1, 19],
       [ 2, 18, 16,  2, 16],
       [ 8,  0, 17,  3,  7],
       [10, 19, 14,  7, 14],
       [14, 12, 11, 16, 13]])

In [77]:
a7 = np.random.randint(0,10,size=(2,3,2,2))
a7

array([[[[5, 5],
         [2, 1]],

        [[5, 7],
         [3, 4]],

        [[1, 5],
         [8, 3]]],


       [[[5, 0],
         [3, 4]],

        [[5, 2],
         [5, 8]],

        [[3, 2],
         [8, 9]]]])