### 作业：

In [1]:
import numpy as np

1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [5]:
n1 = np.zeros(10,dtype=int)
n1[4] = 1
n1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2、创建一个元素为从10到49的ndarray对象

In [10]:
n1 = np.arange(10,50)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3、将第2题的所有元素位置反转

In [11]:
n1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [18]:
n1 = np.random.random((10,10))
display(n1.max(),n1.min())

0.9838775828987804

0.025395307809254364

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [236]:
n1 = np.ones((10,10))
n1[1:-1,1:-1] = 0
n1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

6、创建一个每一行都是从0到4的5*5矩阵

In [43]:
n1 = np.arange(0,5)
n2 = np.zeros(5, dtype=int).reshape((5,1))
n1+n2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [45]:
np.linspace(0,1,num=12,endpoint=True)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序

In [51]:
np.sort(np.random.random(10))

array([0.18979659, 0.19248017, 0.22703171, 0.27210077, 0.44800512,
       0.58876642, 0.65331449, 0.68465817, 0.70056761, 0.90163815])

9、创建一个长度为10的随机数组并将最大值替换为0

In [80]:
np.random.seed()
n1 = np.sort(np.random.rand(10))
n1

array([0.13460393, 0.13828328, 0.16591882, 0.26462209, 0.40967741,
       0.52685098, 0.53069765, 0.86347266, 0.89573696, 0.96894058])

In [83]:
n1[-1] = 0
n1

array([0.13460393, 0.13828328, 0.16591882, 0.26462209, 0.40967741,
       0.52685098, 0.53069765, 0.86347266, 0.89573696, 0.        ])

10、如何根据第3列来对一个5*5矩阵排序？

In [102]:
n1 

array([[61, 35, 65, 60, 76],
       [75, 66, 90, 37, 39],
       [95, 86,  0, 95, 69],
       [58, 27, 98,  7, 21],
       [71, 69, 18, 95, 74]])

In [120]:
n2 = np.argsort(n1[2]).reshape(5,1)
n2

array([[2],
       [4],
       [1],
       [0],
       [3]], dtype=int64)

In [121]:
n1[n2]

array([[[95, 86,  0, 95, 69]],

       [[71, 69, 18, 95, 74]],

       [[75, 66, 90, 37, 39]],

       [[61, 35, 65, 60, 76]],

       [[58, 27, 98,  7, 21]]])

11、给定一个4维矩阵，如何得到最后两维的和？

In [324]:
n1 = np.random.randint(10,size=(2,3,3,2))
n1
n1.sum(axis=(-1,-2))


array([[12, 23, 22],
       [34, 24, 23]])

12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [145]:
n1 = np.array([1,2,3,4,5]).reshape(5,1)
n2 = np.zeros((5,3))
np.hstack((n1,n2)).reshape(1,20)[:,:-3]

array([[1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0.,
        5.]])

13、给定一个二维矩阵，如何交换其中两行的元素？

In [191]:
n1 = np.random.randint(10,size=(3,4))
n1

array([[9, 5, 4, 5],
       [7, 2, 2, 7],
       [3, 6, 4, 3]])

In [192]:
n1[1], n1[2] = n1[2].copy(), n1[1].copy()
n1

array([[9, 5, 4, 5],
       [3, 6, 4, 3],
       [7, 2, 2, 7]])

14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [203]:
%%timeit
np.random.randint(1000,size=(1,10000))**3

161 µs ± 9.56 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [205]:
%%timeit
np.power(np.random.randint(1000,size=(1,10000)),3)

158 µs ± 2.99 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


15、创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积

In [210]:
n1 = np.random.randint(10,size=(5,3))
n2 = np.random.randint(10,size=(3,2))

np.dot(n1,n2)

array([[ 79, 127],
       [ 27,  27],
       [ 37,  93],
       [ 58, 122],
       [ 40,  88]])

16、矩阵的每一行的元素都减去该行的平均值

In [212]:
n1 = np.random.randint(10,size=(5,5))
n1

array([[4, 4, 2, 9, 1],
       [9, 9, 9, 5, 7],
       [2, 7, 9, 8, 5],
       [8, 0, 4, 3, 2],
       [3, 0, 5, 8, 3]])

In [225]:
n1 - np.mean(n1,axis=1).reshape(5,1)

array([[ 0. ,  0. , -2. ,  5. , -3. ],
       [ 1.2,  1.2,  1.2, -2.8, -0.8],
       [-4.2,  0.8,  2.8,  1.8, -1.2],
       [ 4.6, -3.4,  0.6, -0.4, -1.4],
       [-0.8, -3.8,  1.2,  4.2, -0.8]])

17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：
- [[0 1 0 1 0 1 0 1]
- [1 0 1 0 1 0 1 0]
- [0 1 0 1 0 1 0 1]
- [1 0 1 0 1 0 1 0]
- [0 1 0 1 0 1 0 1]
- [1 0 1 0 1 0 1 0]
- [0 1 0 1 0 1 0 1]
- [1 0 1 0 1 0 1 0]]

In [230]:
n1 = np.zeros((8,8))
n1

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [232]:
n1[1::2,::2] = 1
n1[::2,1::2] = 1
n1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

18、正则化一个5*5随机矩阵
正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

In [248]:
n1 = np.random.randint(100,size=(5,5))
n1

array([[81, 72, 91, 78, 77],
       [87, 32, 60, 14, 58],
       [26, 47, 99, 32, 87],
       [61, 31, 36, 31, 77],
       [94, 83, 19, 75, 42]])

In [249]:
nmax, nmin = n1.max(), n1.min()
display(nmax,nmin)
n1 = (n1 - nmin) / (nmax - nmin)
n1

99

14

array([[0.78823529, 0.68235294, 0.90588235, 0.75294118, 0.74117647],
       [0.85882353, 0.21176471, 0.54117647, 0.        , 0.51764706],
       [0.14117647, 0.38823529, 1.        , 0.21176471, 0.85882353],
       [0.55294118, 0.2       , 0.25882353, 0.2       , 0.74117647],
       [0.94117647, 0.81176471, 0.05882353, 0.71764706, 0.32941176]])

19、将一个一维数组转化为二进制表示矩阵。例如
[1,2,3]
转化为
[[0,0,1],
[0,1,0],
[0,1,1]]

In [353]:
n1 = np.array([1,2,3])
n1 = n1.reshape((-1,1))
n1

array([[1],
       [2],
       [3]])

array([[1],
       [2],
       [3]])

20、实现快速和选择排序法

In [296]:
# 快速排序
n1 = np.random.randint(100,size=(10))
n1

for i in range(len(n1)):
    for j in range(len(n1) - 1):
        if n1[i] > n1[j]:
            n1[i], n1[j] = n1[j], n1[i]
n1

array([72, 62, 57, 47, 46, 40, 33, 29, 22, 12])

In [299]:
# 选择排序
n1 = np.random.randint(100,size=(10))
n1

for i in range(len(n1)):
    for j in range(i+ 1, len(n1)):
        if n1[i] > n1[j]:
            n1[i], n1[j] = n1[j], n1[i]
n1

array([ 2, 16, 30, 43, 54, 57, 64, 67, 70, 72])