1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [1]:
import numpy as np

In [3]:
n=np.random.randint(1,size=(10))
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
n[4]=1
n

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2、创建一个元素为从10到49的ndarray对象

In [10]:
n=np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3、将第2题的所有元素位置反转

In [11]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [25]:
n = np.random.random(size=(10,10))
n.min()

0.010888475900142636

In [26]:
n.max()

0.9825910253586966

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [44]:
n=np.full(shape=(10,10), fill_value=1)
n[1:-1,1:-1]= 0
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

6、创建一个每一行都是从0到4的5*5矩阵

In [45]:
n1 = np.arange(0,5)
n2 = n=np.full(shape=(5,5), fill_value=1)
n2[0:5]=n1
n2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [55]:
np.linspace(0, 1, num=12, endpoint=False)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667])

8、创建一个长度为10的随机数组并排序

In [59]:
n = np.random.randint(0,100,size=(10),dtype=int)
np.sort(n)

array([ 0,  4,  6,  7,  7, 17, 28, 29, 38, 46])

9、创建一个长度为10的随机数组并将最大值替换为0

In [66]:
n = np.random.randint(0,100,size=(10))
n[n1.argmax()]=0
n

array([ 8, 78,  3,  0, 47, 97, 41, 68, 44, 55])

10、如何根据第3列来对一个5*5矩阵排序？

In [83]:
n = np.random.randint(0,100,size=(5,5))
n

array([[42, 94, 54, 55, 98],
       [47, 80, 31, 99,  9],
       [72, 88, 12, 26, 78],
       [ 5, 61, 24,  3, 66],
       [40, 83, 64, 78, 62]])

In [84]:
sort_n = np.argsort(n[:,3])
sort_n

array([3, 2, 0, 4, 1], dtype=int64)

In [86]:
n[sort_n]

array([[ 5, 61, 24,  3, 66],
       [72, 88, 12, 26, 78],
       [42, 94, 54, 55, 98],
       [40, 83, 64, 78, 62],
       [47, 80, 31, 99,  9]])

11、给定一个4维矩阵，如何得到最后两维的和？

In [88]:
n=np.random.randint(0,10,size=(2,3,3,2))
n

array([[[[8, 8],
         [3, 7],
         [9, 5]],

        [[2, 6],
         [9, 8],
         [4, 1]],

        [[1, 9],
         [6, 4],
         [9, 7]]],


       [[[9, 3],
         [6, 5],
         [2, 1]],

        [[1, 4],
         [3, 4],
         [4, 4]],

        [[4, 1],
         [6, 8],
         [5, 4]]]])

In [89]:
n.sum(axis=-1)
n.sum(axis=-2)
n.sum(axis=(-1,-2))

array([[40, 30, 36],
       [26, 20, 28]])

12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [168]:
n1 = [1, 2, 3, 4, 5]
n2=np.vstack(n1)
n2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [169]:
n3=np.full(shape=(5,3), fill_value=0)
n3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [170]:
n4=np.concatenate([n2,n3],axis=1)
n4

array([[1, 0, 0, 0],
       [2, 0, 0, 0],
       [3, 0, 0, 0],
       [4, 0, 0, 0],
       [5, 0, 0, 0]])

In [180]:
n4.reshape(-1)[:17]

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

13、给定一个二维矩阵，如何交换其中两行的元素？

In [127]:
n = np.random.randint(0,10,size=(4,4))
n

array([[9, 5, 3, 5],
       [0, 7, 8, 0],
       [9, 1, 4, 7],
       [8, 8, 9, 1]])

In [128]:
n1=n[1:2].copy()
n2=n[2:3].copy()

In [129]:
n[1:2]=n2
n[2:3]=n1
n

array([[9, 5, 3, 5],
       [9, 1, 4, 7],
       [0, 7, 8, 0],
       [8, 8, 9, 1]])

14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [132]:
n=np.random.randint(10000,100000,5)
n

array([89813, 18180, 55900, 72162, 47281])

In [133]:
%timeit np.power(n, 3)

928 ns ± 67.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [136]:
n1 = np.dot(n,n)

In [137]:
%timeit np.dot(n1,n)

892 ns ± 7.04 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


15、创建一个53随机矩阵和一个32随机矩阵，求矩阵积

In [142]:
n1 = np.random.randint(0,10,size=(5,3))
n1

array([[7, 2, 4],
       [0, 1, 2],
       [5, 8, 1],
       [4, 6, 9],
       [0, 4, 0]])

In [143]:
n2 = np.random.randint(0,10,size=(3,2))
n2

array([[4, 2],
       [5, 5],
       [8, 6]])

In [145]:
np.dot(n1,n2)

array([[ 70,  48],
       [ 21,  17],
       [ 68,  56],
       [118,  92],
       [ 20,  20]])

16、矩阵的每一行的元素都减去该行的平均值

In [146]:
n = np.random.randint(0,10,size=(5,5))
n

array([[4, 0, 2, 7, 6],
       [9, 7, 8, 1, 3],
       [7, 7, 0, 4, 7],
       [8, 0, 8, 0, 5],
       [1, 1, 5, 6, 8]])

In [147]:
n1 = np.mean(n,axis=1)
n2 = np.vstack(n1)
n2

array([[3.8],
       [5.6],
       [5. ],
       [4.2],
       [4.2]])

In [148]:
n-n2

array([[ 0.2, -3.8, -1.8,  3.2,  2.2],
       [ 3.4,  1.4,  2.4, -4.6, -2.6],
       [ 2. ,  2. , -5. , -1. ,  2. ],
       [ 3.8, -4.2,  3.8, -4.2,  0.8],
       [-3.2, -3.2,  0.8,  1.8,  3.8]])

17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：

[[0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]]

 Z[1::2,::2] = 1

Z[::2,1::2] = 1


In [158]:
n=np.zeros(shape=(8,8),dtype=int)

In [160]:
n[1::2,::2] = 1
n[::2,1::2] = 1
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

18、正则化一个5*5随机矩阵

正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)


In [182]:
n = np.random.randint(0,100,size=(5,5))
n

array([[66,  7, 89, 55, 63],
       [25, 88, 12, 53, 72],
       [70, 82, 16, 34, 49],
       [98, 11, 96, 83, 31],
       [47, 29, 47,  7,  9]])

In [184]:
max_n = np.max(n)
min_n = np.min(n)
display(max_n,min_n)

98

7

In [185]:
n=(n-min_n)/(max_n-min_n)
n

array([[0.64835165, 0.        , 0.9010989 , 0.52747253, 0.61538462],
       [0.1978022 , 0.89010989, 0.05494505, 0.50549451, 0.71428571],
       [0.69230769, 0.82417582, 0.0989011 , 0.2967033 , 0.46153846],
       [1.        , 0.04395604, 0.97802198, 0.83516484, 0.26373626],
       [0.43956044, 0.24175824, 0.43956044, 0.        , 0.02197802]])

20、实现快速和选择排序法

In [200]:
n = np.random.randint(0,100,size=(5))
n

array([30, 12, 17, 38, 40])

In [201]:
def select(arr):
    for i in range(len(arr)-1):
        index = np.argmin(arr[i:]) + i
        if arr[i]> arr[index]:
            arr[i], arr[index] = arr[index], arr[i]
    return arr

In [202]:
a = np.array(n)

In [203]:
select(a)

array([12, 17, 30, 38, 40])

In [204]:
np.sort(n)

array([12, 17, 30, 38, 40])