## 1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [2]:
import numpy as np

In [11]:
a1 = np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
a1[4]=1

In [13]:
display(a1)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 2、创建一个元素为从10到49的ndarray对象

In [14]:
a2 = np.arange(10,50)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3、将第2题的所有元素位置反转

In [15]:
a3 = n[::-1]
a3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [19]:
a4 = np.random.random(size=(10,10))
a4

array([[0.26831928, 0.18412246, 0.80351334, 0.98992248, 0.56510513,
        0.99889362, 0.48957013, 0.09427325, 0.47258023, 0.44637929],
       [0.4742354 , 0.80160143, 0.68860093, 0.76905242, 0.32892389,
        0.4803152 , 0.88214865, 0.72390718, 0.71589957, 0.20732053],
       [0.62135084, 0.79480307, 0.86945565, 0.73508614, 0.29338569,
        0.7440766 , 0.89110548, 0.19786168, 0.98769599, 0.88183366],
       [0.41019246, 0.98251564, 0.74246199, 0.67201773, 0.15027791,
        0.81855878, 0.45826319, 0.81172066, 0.9591253 , 0.55737276],
       [0.48129625, 0.0445965 , 0.2413455 , 0.9339113 , 0.3726392 ,
        0.93795414, 0.1262967 , 0.9599666 , 0.42842892, 0.89423892],
       [0.13585058, 0.3194218 , 0.91806699, 0.87448206, 0.53591559,
        0.83181933, 0.03540947, 0.76742774, 0.71793194, 0.10066928],
       [0.29763124, 0.71332212, 0.17748075, 0.91164855, 0.09266781,
        0.58929569, 0.9517595 , 0.40144919, 0.37549346, 0.19215656],
       [0.78481669, 0.31503883, 0.4498542

In [21]:
a4.max()

0.9988936192944816

In [22]:
a4.min()

0.011059658800170458

## 5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [24]:
a5 = np.ones((10,10))
a5[1:9,1:9] = 0
a5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 6、创建一个每一行都是从0到4的5*5矩阵

In [32]:
a6_1 = [0,1,2,3,4]
a6_2 = np.array(a6_1 * 5)
a6 = np.reshape(a6_2,(5,5))
a6

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## 7、创建一个范围在(0,1)之间的长度为12的等差数列

In [33]:
a7 = np.linspace(0,1,12)
a7

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

## 8、创建一个长度为10的随机数组并排序

In [34]:
a8 = np.random.random(10)
a8

array([0.08780926, 0.21147261, 0.96810655, 0.21382124, 0.87361639,
       0.72558052, 0.99437265, 0.06667028, 0.6789242 , 0.69189204])

In [36]:
a8.sort()
a8

array([0.06667028, 0.08780926, 0.21147261, 0.21382124, 0.6789242 ,
       0.69189204, 0.72558052, 0.87361639, 0.96810655, 0.99437265])

## 9、创建一个长度为10的随机数组并将最大值替换为0

In [37]:
a9 = np.random.random(10)
a9

array([0.10172489, 0.06057438, 0.55163086, 0.64564157, 0.06271094,
       0.81665414, 0.45546635, 0.23908186, 0.30079285, 0.34679634])

In [41]:
max_index = a9.argmax()
a9[max_index]=0
a9

array([0.10172489, 0.06057438, 0.55163086, 0.        , 0.06271094,
       0.        , 0.45546635, 0.23908186, 0.30079285, 0.34679634])

## 10、如何根据第3列来对一个5*5矩阵排序？

In [43]:
a10 = np.random.randint(1,100,size=(5,5))
a10

array([[63, 98, 51, 58, 23],
       [39, 60, 34, 92, 26],
       [52, 85, 47, 93, 77],
       [17, 42, 58,  3, 25],
       [79, 33, 21, 18, 15]])

In [48]:
np.argsort(a10[:,2])

array([4, 1, 2, 0, 3], dtype=int64)

In [47]:
a10[np.argsort(a10[:,2])]

array([[79, 33, 21, 18, 15],
       [39, 60, 34, 92, 26],
       [52, 85, 47, 93, 77],
       [63, 98, 51, 58, 23],
       [17, 42, 58,  3, 25]])

## 11、给定一个4维矩阵，如何得到最后两维的和？

In [50]:
a11 = np.random.randint(0,100,size=(4,3,2,5))
a11

array([[[[ 4, 82, 58, 68, 63],
         [99,  9,  1, 94, 95]],

        [[85, 81, 83, 19, 21],
         [61, 96,  2,  7, 86]],

        [[43, 84, 56, 55, 79],
         [48, 82, 84, 66, 90]]],


       [[[30, 71, 93, 60, 50],
         [74, 58, 72, 20, 37]],

        [[83, 23, 87, 31, 62],
         [29, 80, 14, 67, 33]],

        [[28, 70, 10, 75, 35],
         [93, 55,  2, 50, 83]]],


       [[[30, 20,  6, 97, 84],
         [47, 74, 93, 38, 82]],

        [[91, 11,  0,  4,  2],
         [15, 85, 62, 55, 37]],

        [[65, 69, 87, 31, 60],
         [ 2, 23, 39, 28, 80]]],


       [[[86,  9, 92, 24, 27],
         [33, 93, 74, 57, 54]],

        [[96, 49, 60, 20, 95],
         [27, 78, 36, 75, 17]],

        [[48, 49, 41, 70, 26],
         [ 7, 77, 94, 29, 59]]]])

In [61]:
#第三维的和
a11.sum(axis=2)

array([[[103,  91,  59, 162, 158],
        [146, 177,  85,  26, 107],
        [ 91, 166, 140, 121, 169]],

       [[104, 129, 165,  80,  87],
        [112, 103, 101,  98,  95],
        [121, 125,  12, 125, 118]],

       [[ 77,  94,  99, 135, 166],
        [106,  96,  62,  59,  39],
        [ 67,  92, 126,  59, 140]],

       [[119, 102, 166,  81,  81],
        [123, 127,  96,  95, 112],
        [ 55, 126, 135,  99,  85]]])

In [62]:
#第四维的和
a11.sum(axis=3)

array([[[275, 298],
        [289, 252],
        [317, 370]],

       [[304, 261],
        [286, 223],
        [218, 283]],

       [[237, 334],
        [108, 254],
        [312, 172]],

       [[238, 311],
        [320, 233],
        [234, 266]]])

## 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [66]:
a12_1 = np.array([1,2,3,4,5]).reshape(5,1)
a12_1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [69]:
a12_2 = np.zeros((5,3))
a12_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
a12 = np.concatenate([a12_1,a12_2],axis=1)
a12

array([[1., 0., 0., 0.],
       [2., 0., 0., 0.],
       [3., 0., 0., 0.],
       [4., 0., 0., 0.],
       [5., 0., 0., 0.]])

## 13、给定一个二维矩阵，如何交换其中两行的元素？

In [76]:
a13 = np.random.randint(0,100,size=(4,3))
a13

array([[48, 39, 13],
       [82, 21, 57],
       [48, 14, 80],
       [13, 23, 54]])

In [77]:
#交换索引
a13[[1,0,2,3]]

array([[82, 21, 57],
       [48, 39, 13],
       [48, 14, 80],
       [13, 23, 54]])

## 14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [80]:
a14 =  np.random.random(size=100000)
a14

array([0.88123753, 0.48380861, 0.97015463, ..., 0.19633086, 0.37569421,
       0.62336992])

In [81]:
%timeit np.power(a14,3)

5.26 ms ± 88.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [82]:
%timeit a14**3

5.51 ms ± 376 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


 ## 15、创建一个5 * 3随机矩阵和一个3 * 2随机矩阵，求矩阵积

In [83]:
a15_1 = np.random.randint(0,100,size=(5,3))
a15_1

array([[67, 61,  7],
       [62, 79, 41],
       [21, 11, 89],
       [23, 57, 23],
       [ 5, 20, 22]])

In [84]:
a15_2 = np.random.randint(0,100,size=(3,2))
a15_2

array([[15, 47],
       [35, 58],
       [72, 48]])

In [85]:
np.dot(a15_1,a15_2)

array([[3644, 7023],
       [6647, 9464],
       [7108, 5897],
       [3996, 5491],
       [2359, 2451]])

## 16、矩阵的每一行的元素都减去该行的平均值

In [6]:
a16 = np.random.randint(0,100,size=(4,3))
a16

array([[ 4, 89, 33],
       [82, 71, 14],
       [74, 46, 67],
       [33, 78, 61]])

In [8]:
a16_mean = np.mean(a16,axis=1)
a16_m = np.vstack(a16_mean)
a16_m

array([[42.        ],
       [55.66666667],
       [62.33333333],
       [57.33333333]])

In [9]:
a16 - a16_m

array([[-38.        ,  47.        ,  -9.        ],
       [ 26.33333333,  15.33333333, -41.66666667],
       [ 11.66666667, -16.33333333,   4.66666667],
       [-24.33333333,  20.66666667,   3.66666667]])