In [17]:
import numpy as np

### 1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 2 、创建一个元素为从10到49的ndarray对象

In [30]:
n = np.linspace(10,49, num=40,dtype=int)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
n_1 = np.arange(10,49,step=1)
n_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

### 3、将第2题的所有元素位置反转

In [32]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

 ### 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [80]:
n4_1 = np.random.random((10,10))


n4_1

array([[0.71769832, 0.12932991, 0.2672246 , 0.60342953, 0.79739021,
        0.65536334, 0.66728505, 0.67335406, 0.8674863 , 0.94853227],
       [0.9226124 , 0.25759259, 0.13939224, 0.78189612, 0.20166852,
        0.36358539, 0.2775446 , 0.71036059, 0.59071024, 0.97513306],
       [0.07608886, 0.32190662, 0.56265576, 0.06971122, 0.73351695,
        0.60883032, 0.00882983, 0.76665265, 0.74983496, 0.6804166 ],
       [0.54420415, 0.58295758, 0.23353655, 0.29734029, 0.63941172,
        0.76108688, 0.95220767, 0.74640326, 0.48669383, 0.2576354 ],
       [0.90449054, 0.52717664, 0.95623812, 0.40839777, 0.04357244,
        0.31195505, 0.91068701, 0.43034342, 0.65000712, 0.91662221],
       [0.42839483, 0.45152303, 0.19375547, 0.93363526, 0.88229688,
        0.89802965, 0.98806807, 0.89415829, 0.19800144, 0.40832565],
       [0.5038171 , 0.33452981, 0.66855818, 0.75094136, 0.6283322 ,
        0.09345177, 0.22466044, 0.20748054, 0.42142223, 0.41067341],
       [0.30035978, 0.64064248, 0.4525044

In [50]:
np.random.random(10)

array([0.80054987, 0.52707889, 0.60248158, 0.49660027, 0.34984057,
       0.86777915, 0.12242425, 0.10661558, 0.62638158, 0.4490219 ])

### 5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [76]:

n5 = np.ones((10,10,),dtype=int)
n5[1:-1,1:-1]=0

n5

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 6、创建一个每一行都是从0到4的5*5矩阵

In [91]:
n6 = np.zeros((5,5),dtype=int)
n6[:,1:2]=1
n6[:,2:3]=2
n6[:,3:4]=3
n6[:,4:]=4
n6

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 7、创建一个范围在(0,1)之间的长度为12的等差数列

In [101]:
# np.random.random(12)
# n = np.arange(0,1,12 )
n = np.linspace(0, 1, num=12)
n

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

### 8、创建一个长度为10的随机数组并排序

In [9]:
n = np.random.randint(0,100,size=10)
n
def bubble(n):
    for i in range(len(n) -1):
        for j in range(i+1, len(n)):
            if n[i] > n[j]:
                n[i], n[j] = n[j], n[i]
bubble(n)
n

array([12, 15, 24, 27, 35, 38, 39, 40, 65, 81])

### 9、创建一个长度为10的随机数组并将最大值替换为0

In [11]:
n9 = np.random.randint(0,100,size=10)
n9[n9.argmax()]=0
n9

array([34, 37,  8, 10, 36, 66, 26,  1, 43,  0])

### 10、如何根据第3列来对一个5*5矩阵排序？

In [66]:
n10 = np.random.randint(0,100,size=(5,5))
n10
n10_1=np.argsort(n10[:,2])
n10_1
n10[n10_1]
# n10[array([4, 0, 2, 3, 1], dtype=int64)]



array([[70, 99, 41, 44, 30],
       [11, 88, 50, 48, 26],
       [63, 10, 69, 21, 56],
       [11, 48, 90, 68, 87],
       [11, 66, 90,  1, 47]])

### 11、给定一个4维矩阵，如何得到最后两维的和？

In [67]:
nd11=np.random.randint(0,10,size=(2,3,2,2))
nd11.sum(axis=(-1,-2))

array([[14, 10, 20],
       [26, 13, 11]])

### 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [ ]:
n12 = [1,2,3,4,5]

### 13、给定一个二维矩阵，如何交换其中两行的元素？

In [70]:
n13=np.random.randint(0,20,size=(3,4))
n13[[1,2,0]]

array([[ 5, 14, 14, 18],
       [15,  4, 10, 19],
       [ 6, 14, 15,  2]])

In [69]:
n13[[1,2,0]]

NameError: name 'n13' is not defined